"""Generate a self-contained Colab submission notebook from the repo.

The `src/` package and `configs/` are the single source of truth. This script embeds each
file (base64-encoded, so any quoting/newlines survive), so the notebook writes them to disk
and then runs the exact `python -m src.train` / `src.predict` code paths we tested locally.
No external repo clone is needed, which is the most reproducible option for the grader.

Usage:
    python tools/build_submission_notebook.py            # -> notebooks/submission.ipynb
"""
from __future__ import annotations

import base64
import glob
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "notebooks", "submission.ipynb")

# Files bundled into the notebook (source of truth).
FILES = sorted(glob.glob("src/*.py")) + sorted(glob.glob("configs/*.yaml")) + ["requirements.txt"]

# Which config the notebook trains by default. Run 2 (BERT + cross-attention) is the main
# model; a plain "Run all" trains it end-to-end with no manual cell edits. Switch back to
# configs/resnet50_concat.yaml here to reproduce the safety-net run.
DEFAULT_CONFIG = "configs/vit_bert_attn.yaml"


def code(src: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}


def md(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src}


def build() -> dict:
    payload = {}
    for rel in FILES:
        with open(os.path.join(REPO, rel), "rb") as f:
            payload[rel] = base64.b64encode(f.read()).decode("ascii")

    write_cell = (
        "# 1. Materialize the project files (src/ + configs/) — single source of truth, embedded.\n"
        "import base64, os, json\n"
        f"FILES = json.loads(r'''{json.dumps(payload)}''')\n"
        "for path, b64 in FILES.items():\n"
        "    os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None\n"
        "    with open(path, 'wb') as fh:\n"
        "        fh.write(base64.b64decode(b64))\n"
        "open('src/__init__.py', 'a').close()\n"
        "print('wrote', len(FILES), 'files')\n"
        "!pip install -q -r requirements.txt"
    )

    data_cell = (
        "# 2. Data: mount Drive, copy data.zip (prepared by data_download_VQA.ipynb), unzip.\n"
        "#    Produces data/train.json, data/valid.json, data/train/, data/valid/\n"
        "from google.colab import drive\n"
        "drive.mount('/content/drive')\n"
        "!cp \"/content/drive/MyDrive/data.zip\" .\n"
        "!unzip -q -o data.zip\n"
        "!ls data"
    )

    cfg_name = os.path.splitext(os.path.basename(DEFAULT_CONFIG))[0]
    train_cell = (
        f"# 3. Train the model ({cfg_name}). Swap CONFIG for another file in configs/ to reproduce\n"
        "#    a different ablation row (e.g. resnet50_concat for the safety-net baseline).\n"
        f"CONFIG = '{DEFAULT_CONFIG}'\n"
        "!python -m src.train --config $CONFIG"
    )
    predict_cell = (
        "# 4. Write submission.npy (answer strings) + model.pt from the best checkpoint\n"
        f"CKPT = 'experiments/{cfg_name}/best.pt'\n"
        "!python -m src.predict --config $CONFIG --ckpt $CKPT --out submission/submission.npy"
    )
    verify_cell = (
        "# 5. Verify the submission format before packaging\n"
        "import numpy as np\n"
        "a = np.load('submission/submission.npy')\n"
        "print('shape', a.shape, 'dtype', a.dtype)\n"
        "assert a.shape == (4969,), 'test set has 4969 samples'\n"
        "assert a.dtype.kind in ('U', 'S', 'O'), 'answers must be strings'\n"
        "print('submission.npy OK')"
    )
    zip_cell = (
        "# 6. Zip the three required artifacts (<=4.5GB) and submit submission.zip to Omnicampus\n"
        "import os\n"
        "from zipfile import ZipFile\n"
        "NOTEBOOK = '/content/drive/MyDrive/Colab Notebooks/submission.ipynb'  # adjust to this notebook's path\n"
        "with ZipFile('submission.zip', 'w') as zf:\n"
        "    zf.write('submission/submission.npy', arcname='submission.npy')\n"
        "    zf.write('submission/model.pt', arcname='model.pt')\n"
        "    zf.write(NOTEBOOK, arcname='submission.ipynb')\n"
        "size_gb = os.path.getsize('submission.zip') / 1e9\n"
        "print(f'submission.zip = {size_gb:.2f} GB')\n"
        "assert size_gb <= 4.5, 'zip exceeds 4.5GB limit'"
    )

    cells = [
        md(
            "# VQA competition — self-contained submission notebook\n\n"
            "Runs top-to-bottom with no external repo: cell 1 writes the `src/` package and\n"
            "`configs/` to disk (embedded, base64), then normal `python -m src.train` / `src.predict`\n"
            "calls train and produce `submission.npy` + `model.pt`. Generated by\n"
            "`tools/build_submission_notebook.py` — edit `src/`, regenerate, do not hand-edit.\n\n"
            "**Prereq:** `data.zip` (12GB) on Google Drive (see `data_download_VQA.ipynb`).\n"
            "Strategy: run `resnet50_concat` first and submit early (safety net), then rerun with\n"
            "`vit_bert_attn` for the improved score. Only the last submission is graded and it must\n"
            "stay >= 49.9%."
        ),
        code(write_cell),
        code(data_cell),
        code(train_cell),
        code(predict_cell),
        code(verify_cell),
        code(zip_cell),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


if __name__ == "__main__":
    nb = build()
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print(f"wrote {OUT}  ({len(nb['cells'])} cells, {len(FILES)} embedded files)")
